### ISSUE TITLE
Translation API

### ISSUE THREAD

**Issue by diogolopes18-cyber** [diogolopes18-cyber/IEEE_ISEP_Discord_Bot#17]
Include a translation API in order to translate user provided strings

## Task breakdown

* [x] Research about translation APIs
* [x] Include API into project
* [x] Implement a command for translating from one language to another based on user choice
* [x] Implement command to translate string and detect language (translate into English)
